Repository KAU2024-SANHAK/SANHAK_Server, pull requests merged in 2024-04, with the labels that each got.

#13 [chore] CI/CD settings
  .github/workflows/CD-dev.yml
  .github/workflows/CI-dev.yml
  build.gradle
  scripts/appspec.yml
  scripts/deploy.sh
  scripts/switch.sh
  src/main/java/org/kau/kkoolbeeServer/global/common/config/AWSConfig.java
  src/main/java/org/kau/kkoolbeeServer/global/common/controller/ServerProfileController.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/ApiResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/ErrorType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/SuccessType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/exception/GlobalExceptionHandler.java
  src/main/java/org/kau/kkoolbeeServer/global/common/exception/model/CustomException.java
  src/main/resources/application-dev1.yml
  src/main/resources/application-dev2.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: chore

#15 Feat/#14 entity
  src/main/java/org/kau/kkoolbeeServer/KkoolbeeServerApplication.java
  src/main/java/org/kau/kkoolbeeServer/domain/advice/Advice.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Diary.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Feeling.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/Member.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/UserDiaryType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/domain/BaseTimeEntity.java
Labels: feat

#23 Refactor/#22 entity feeling retouch
  src/main/java/org/kau/kkoolbeeServer/domain/advice/Advice.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Diary.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Feeling.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/Member.java
  src/main/java/org/kau/kkoolbeeServer/domain/summary/Summary.java
Labels: feat

#31 feat: 카카오 로그인 구현+s3서버 세팅
  build.gradle
  src/main/java/org/kau/kkoolbeeServer/KkoolbeeServerApplication.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/Member.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/controller/MemberController.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/dto/response/MemberLoginResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/repository/MemberRepository.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/service/MemberService.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/KakaoApiClient.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/KakaoAuthApiClient.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/KakaoLoginService.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoAccount.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoUserProfile.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoUserResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/jwt/JwtProvider.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/jwt/TokenDto.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/redis/RefreshToken.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/redis/TokenRepository.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/AuthWhiteList.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/JwtExceptionFilter.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/UserAuthentication.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/ErrorType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/SuccessType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/exception/GlobalExceptionHandler.java
  src/main/java/org/kau/kkoolbeeServer/global/config/RedisConfig.java
  src/main/java/org/kau/kkoolbeeServer/global/config/SecurityConfig.java
  src/main/resources/application-dev1.yml
  src/main/resources/application-dev2.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feat

#32 Feat/#30 slowtype save api
  src/main/java/org/kau/kkoolbeeServer/KkoolbeeServerApplication.java
  src/main/java/org/kau/kkoolbeeServer/S3/S3UploaderService.java
  src/main/java/org/kau/kkoolbeeServer/domain/advice/Advice.java
  src/main/java/org/kau/kkoolbeeServer/domain/advice/dto/AdviceResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Diary.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/controller/DiaryController.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/request/CurrentDateRequestDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/request/DiaryContentRequestDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/request/FeelingListRequestDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/CalenderDiaryResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/DiaryContentResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/FeelingListResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/SlowTypeCreateResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/repository/DiaryRepository.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/service/DiaryService.java
  src/main/java/org/kau/kkoolbeeServer/global/common/domain/BaseTimeEntity.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/ApiResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/ErrorType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/SuccessType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/exception/GlobalExceptionHandler.java
  src/main/java/org/kau/kkoolbeeServer/global/config/S3Config.java
  src/main/resources/application.yml
  src/test/java/org/kau/kkoolbeeServer/domain/diary/controller/DiaryControllerTest.java
Labels: feat

#33 Develop에서 main merge
  build.gradle
  node_modules/.yarn-integrity
  src/main/java/org/kau/kkoolbeeServer/KkoolbeeServerApplication.java
  src/main/java/org/kau/kkoolbeeServer/S3/S3UploaderService.java
  src/main/java/org/kau/kkoolbeeServer/domain/advice/Advice.java
  src/main/java/org/kau/kkoolbeeServer/domain/advice/dto/AdviceResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Diary.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/Feeling.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/controller/DiaryController.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/request/CurrentDateRequestDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/request/DiaryContentRequestDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/request/FeelingListRequestDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/CalenderDiaryResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/DiaryContentResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/FeelingListResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/dto/response/SlowTypeCreateResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/repository/DiaryRepository.java
  src/main/java/org/kau/kkoolbeeServer/domain/diary/service/DiaryService.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/Member.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/UserDiaryType.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/controller/MemberController.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/dto/response/MemberLoginResponseDto.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/repository/MemberRepository.java
  src/main/java/org/kau/kkoolbeeServer/domain/member/service/MemberService.java
  src/main/java/org/kau/kkoolbeeServer/domain/summary/Summary.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/KakaoApiClient.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/KakaoAuthApiClient.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/KakaoLoginService.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoAccessTokenResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoAccount.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoUserProfile.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/fegin/kakao/response/KakaoUserResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/jwt/JwtProvider.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/jwt/TokenDto.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/redis/RefreshToken.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/redis/TokenRepository.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/AuthWhiteList.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/JwtExceptionFilter.java
  src/main/java/org/kau/kkoolbeeServer/global/auth/security/UserAuthentication.java
  src/main/java/org/kau/kkoolbeeServer/global/common/domain/BaseTimeEntity.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/ApiResponse.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/ErrorType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/dto/enums/SuccessType.java
  src/main/java/org/kau/kkoolbeeServer/global/common/exception/GlobalExceptionHandler.java
  src/main/java/org/kau/kkoolbeeServer/global/config/RedisConfig.java
  src/main/java/org/kau/kkoolbeeServer/global/config/S3Config.java
  src/main/java/org/kau/kkoolbeeServer/global/config/SecurityConfig.java
  src/main/resources/application-dev1.yml
  src/main/resources/application-dev2.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/org/kau/kkoolbeeServer/domain/diary/controller/DiaryControllerTest.java
  yarn.lock
Labels: merge

#36 [refactor] 카카오 인가코드 프론트측엫서 받아오는 방식으로 수정
  src/main/java/org/kau/kkoolbeeServer/domain/member/controller/MemberController.java
  src/main/java/org/kau/kkoolbeeServer/global/config/JpaAuditingConfig.java
  src/main/java/org/kau/kkoolbeeServer/global/config/WebConfig.java
Labels: refactor
